[package]
name = "feo-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
feo-types = { path = "../feo-types" }
feo-error = { path = "../feo-error" }