#[derive(Debug)]
pub enum LexErrorKind {
    UnopenedBlockComment,
    UnclosedBlockComment,
    MismatchedDelimiters,
    UnclosedDocComment,
    UnclosedDelimiter,
    UnclosedStringLiteral,
    UnclosedCharLiteral,
    EmptyCharLiteral,
    ExpectedCharLiteral,
    ExpectedClosingSingleQuote,
    ExpectedClosingDoubleQuote,
    UnexpectedIdentifier(String),
    InvalidEscapeSequence,
    ExpectedEscapeSequence,
    MismatchedTokenType,
    ExpectedToken,
    ExpectedTokenTree,
    ReachedFinalIndex,
    InvalidKeyword(String),
    UnrecognizedDelimKind(char),
    ParseError,
    ParseCharError,
    ParseBoolError,
    ParseIntError,
    ParseUIntError,
    ParseFloatError,
    ParseDelimError,
    ParseCommentError,
    ParseDocCommentError,
    ParseTypeAnnError,
    ParsePathExprError,
    InvalidChar(char),
    UnexpectedChar(char),
}

#[derive(Debug)]
pub struct LexError {
    pub error_kind: LexErrorKind,
    pub pos: usize,
}
