#[derive(Debug, Clone)]
pub enum LexErrorKind {
    UninitializedBlockComment,
    UnterminatedBlockComments,
    ExpectedBlockCommentTerminator,
    MismatchedDelimiters,
    UnclosedDelimiters,
    UnclosedDoubleQuotes,
    UnclosedSingleQuotes,
    EmptyCharLiteral,
    ExpectedCharLiteral,
    ExpectedClosingSingleQuote,
    ExpectedClosingDoubleQuote,
    UnexpectedIdentifier(String),
    InvalidEscapeSequence,
    ExpectedEscapeSequence,
    MismatchedTokenType,
    ExpectedToken,
    ExpectedTokenTree,
    ReachedFinalIndex,
    InvalidKeyword(String),
    UnrecognizedDelimKind(char),
    ParseError,
    ParseCharError,
    ParseBoolError,
    ParseIntError,
    ParseUIntError,
    ParseFloatError,
    ParseDelimError,
    ParseCommentError,
    ParseDocCommentError,
    ParseTypeAnnError,
    ParsePathExprError,
    InvalidChar(char),
    UnexpectedChar(char),
}

#[derive(Debug, Clone)]
pub struct LexError {
    pub error_kind: LexErrorKind,
    pub pos: usize,
}
