pub struct LexError {
    pub error_kind: LexErrorKind,
    pub pos: usize,
}

pub enum LexErrorKind {
    UnclosedBlockComment,
    MismatchedDelimiters,
    UnclosedDocComment,
    UnclosedDelimiter,
    UnclosedStringLiteral,
    UnclosedCharLiteral,
    MismatchedTokenType,
    NoTokenFound,
    UnopenedBlockComment,
    FinalIndex,
    InvalidEscapeSequence,
    InvalidDocCommentContent,
    InvalidCommentContent,
    InvalidKeyword,
    InvalidChar,
    InvalidCharLiteral,
    InvalidDelimiter,
    InvalidPunctuation,
    InvalidIdentifier,
    InvalidPathExpression,
    InvalidTypeAnnotation,
    ExpectedEscapeSequence,
    ParseBoolError,
    ParseIntError,
    ParseUIntError,
    ParseFloatError,
    ParseCharError,
    UnrecognizedDelimiter,
    EmptyCharLiteral,
}
